# SITE CONFIGURATION
title: Mode-Info # your site title
author: formetnicolas # You :P
description: > # Meta description of Homepage
  Découvrez les dernières tendances mode, astuces et conseils pour être stylé(e) de la tête aux pieds. Explorez nos articles sur la mode femme, homme et enfants, trouvez des idées de tenues et apprenez à aménager votre dressing de rêve. Suivez notre blog de mode pour rester à la pointe de la fashion et exprimer votre style unique !
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Mentions Legales', link: '/mentionslegales'}

tagline: >
  Découvrez les dernières tendances mode, astuces et conseils pour être stylé(e) de la tête aux pieds. Explorez nos articles sur la mode femme, homme et enfants, trouvez des idées de tenues et apprenez à aménager votre dressing de rêve. Suivez notre blog de mode pour rester à la pointe de la fashion et exprimer votre style unique !

hero_img: posts/machine-coudre_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
theme: jekyll-sleek